# Generated by Django 5.0 on 2023-12-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.BigIntegerField(null='N/A')),
                ('name', models.CharField(max_length=255, null='N/A')),
                ('sex', models.CharField(max_length=255, null='N/A')),
                ('contact', models.CharField(max_length=255, null='N/A')),
                ('address', models.CharField(max_length=255, null='N/A')),
                ('dept', models.CharField(max_length=255, null='N/A')),
                ('course', models.CharField(max_length=255, null='N/A')),
                ('year', models.BigIntegerField(null='N/A')),
                ('section', models.CharField(max_length=255, null='N/A')),
            ],
        ),
    ]
